package com.hesapgunlugu.app.core.data.local

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(
    tableName = "transactions",
    indices = [
        Index(value = ["date"]),
        Index(value = ["type"]),
        Index(value = ["category"]),
        Index(value = ["date", "type"]),
        // CRITICAL FIX: Unique constraint prevents duplicate recurring transactions
        Index(value = ["scheduledPaymentId", "date"], unique = true),
    ],
)
data class TransactionEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val title: String,
    val amount: Double,
    // Epoch milliseconds
    val date: Long,
    // "INCOME" or "EXPENSE"
    val type: String,
    val category: String,
    // Category emoji
    val emoji: String = "",
    // CRITICAL FIX: Link to scheduled payment if auto-generated by recurring payment worker
    // Null for manual transactions, non-null for automated recurring transactions
    // Enables idempotency check to prevent duplicate transaction creation
    val scheduledPaymentId: Long? = null,
)
