package com.hesapgunlugu.app.core.domain.model

import kotlinx.datetime.Clock
import kotlinx.datetime.Instant
import java.util.Date

/**
 * Represents the type of financial transaction.
 *
 * Used to distinguish between money coming in (income)
 * and money going out (expense).
 */
enum class TransactionType {
    /** Money received (salary, freelance, investments, etc.) */
    INCOME,

    /** Money spent (bills, shopping, subscriptions, etc.) */
    EXPENSE,
}

/**
 * Domain model representing a financial transaction.
 *
 * A transaction records a single financial event - either income or expense.
 * This is the core entity of the finance tracking application.
 *
 * ## Properties
 * - [id]: Unique identifier (auto-generated by database)
 * - [title]: Human-readable description
 * - [amount]: Monetary value (always positive)
 * - [date]: When the transaction occurred
 * - [type]: Whether it's income or expense
 * - [category]: Classification for reporting
 * - [emoji]: Visual indicator for the category
 *
 * ## Usage
 * ```kotlin
 * val transaction = Transaction(
 *     title = "Salary",
 *     amount = 5000.0,
 *     type = TransactionType.INCOME,
 *     category = "Maaş",
 *     emoji = "💰"
 * )
 * ```
 *
 * ## Immutability
 * All properties are `val` (read-only) ensuring thread-safety and predictability.
 *
 * @property id Unique database identifier, 0 for new transactions
 * @property title Short description of the transaction
 * @property amount Transaction value (always positive, type determines sign)
 * @property date Date and time of the transaction
 * @property type Whether this is income or expense
 * @property category Category name for grouping/reporting
 * @property emoji Visual emoji representing the category
 *
 * @see TransactionType
 * @see TransactionRepository
 */
data class Transaction(
    val id: Int = 0,
    val title: String,
    val amount: Double,
    /** Epoch milliseconds */
    val timestamp: Long = Clock.System.now().toEpochMilliseconds(),
    val type: TransactionType,
    val category: String,
    val emoji: String = "",
    val scheduledPaymentId: Long? = null,
) {
    /** Backward compatibility for legacy Date usage. Prefer [instant] or [timestamp]. */
    @Deprecated("Use instant or timestamp")
    val date: Date get() = Date(timestamp)

    /** Preferred time representation */
    val instant: Instant get() = Instant.fromEpochMilliseconds(timestamp)

    @Deprecated("Use primary constructor with timestamp")
    constructor(
        id: Int = 0,
        title: String,
        amount: Double,
        date: Date = Date(),
        type: TransactionType,
        category: String,
        emoji: String = "",
        scheduledPaymentId: Long? = null,
    ) : this(
        id = id,
        title = title,
        amount = amount,
        timestamp = date.time,
        type = type,
        category = category,
        emoji = emoji,
        scheduledPaymentId = scheduledPaymentId,
    )

    /**
     * Returns the signed amount based on transaction type.
     *
     * Positive for income, negative for expense.
     */
    val signedAmount: Double
        get() = if (type == TransactionType.INCOME) amount else -amount

    /**
     * Checks if this is an income transaction.
     */
    val isIncome: Boolean
        get() = type == TransactionType.INCOME

    /**
     * Checks if this is an expense transaction.
     */
    val isExpense: Boolean
        get() = type == TransactionType.EXPENSE
}
